### ISSUE TITLE
[5/31] 価格の実測値を表示する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#100]
## バグの内容
- RL_visualize.pyの関数descr_priceで作成するグラフに実測値が反映されない
- result_inputdata_reference.pyで作成されるresult_dataeframe.csvの実測値が０から変化しない
- 20行目data = pd.read_csv("Battery-Control-By-Reinforcement-Learning/input_data2022_all_0.csv")を/input_data2022.csvに変更しても反映されない

[descr_price.pdf](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/files/15310611/descr_price.pdf)

## 期待される動作
- result_dataframe.csvに実測値が反映され、グラフにも反映される

## 再現方法
- main.pyを実行するとdescr_price関数が機能しグラフが描写される（実測値は０のまま）

## 不明点
- result_inputdata_reference.pyのインプットデータを参照するコードを変更しても、実測値が反映されない

## バグ改修の必要性
- 予測値と実測値のグラフを作成したいのに、実測値が０のまま出力されてしまう

## Issue解決の期限
- 5/31まで

**Comment by daisukekodaira** [comment]
@HashiReo issueを埋めてみて下さい。5/31までで書いてみて下さい。俺もあとで直したりします。

**Comment by HashiReo** [comment]
埋めてみました、画像を張り付けるのがリンクになってしまうので直接出てくるようにします

**Comment by HashiReo** [comment]
グラフにて実測値は反映されましたが、参照する値が１つずれています。これはもともとずれていたため新たに修正します

**Comment by HashiReo** [comment]
参照する値がずれていると考えていたのですが、正しい値を参照していたので変更することはなくなりました。
![スクリーンショット 2024-05-22 153405](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/160702017/45e06bf0-dd6e-4485-952f-de6f1a154c6b)

**Comment by daisukekodaira** [comment]
すばらしい！colseします
