### ISSUE TITLE
[7/3 - 10/7] 1ヶ月の性能評価（ベースvs前日計画) 

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#104]
以下の内容のissueをまず書く：

やること：強化学習なしの場合の収益と比較する（ベースvs前日計画）
欲しい結果：
１ヶ月の連続運転をして、
- 最も結果のいい日(収益が高い)のスケジュールをグラフにする（スライド11枚め）
- 最も結果の悪い日(収益が低い)のスケジュールをグラフにする(スライド11枚め)
- 1ヶ月全体での収益を評価する（スライド15枚目のベースと前日計画）
（ベースというのは蓄電池なしで運用した場合のもの）
期待される内容：
- 蓄電池の動作が人間からみて妥当と思える動作ならok

資料：
[修論発表PPT](https://docs.google.com/presentation/d/1syi_60pCBU3dOlBlI3sqjyNY6iLNdLdr/edit?usp=drive_link&ouid=103151093593261743589&rtpof=true&sd=true)

## 追加したい機能
・前日計画の収益（前日とベース）を棒グラフで表示

## Issueが解決した時に期待される結果
- 実行されたときのイメージを絵・文章で表現

## 実装の指針
・csvから棒グラフを表示するコードを追加

## このIssueの必要性
- 変更のモチベーション、理由

## Issue解決の期限
[Step1] 9/30 １ヶ月分トータルの棒グラフを出す  （スライドP15）
[Step2] 9/30 最も結果のいい日、最も結果の悪い日の棒グラフ（3本）を出す
[Step3] 10/07 リアルタイムの結果が悪い原因を３つ仮説を立てる

**Comment by OsoneYuki** [comment]
改善してtotal_profitは出力できた。
これをグラフにする作業に移る

**Comment by OsoneYuki** [comment]
モデルの学習結果（リワードの推移）と
ベース収益と前日計画収益を比較した結果をグラフで出力しました。

![image](https://github.com/user-attachments/assets/969c60d4-fb40-4f83-b9d7-ffe308b23304)
![image](https://github.com/user-attachments/assets/0527e008-d289-499b-a3d1-ed8220fbda21)
![image](https://github.com/user-attachments/assets/88061e19-7ee7-498f-9936-5a61364d7e09)
