### ISSUE TITLE
[10/15~] 結果のグラフがすべて0になることを確認する

### ISSUE THREAD

**Issue by HashiReo** [SmartGridLab/battery-control-by-reinforcement-learning#114]
## 最終的なゴール
- ①total_profit_bid
- ②totalprofit_realtime
- ③totalprofit_actual_realtime
- ④totalprofit_actual_bid
- 上記の順番になるようなグラフを得ること

## シナリオ
- データ：price_predict.csv, pv_predict.csvを全て0にして実行する
- 欲しい結果：①～④がすべて0で一致する

## 結果
- ①②は0になったが、③④は0にならず。
- 原因は、強化学習による行動が格納される "charge/discharge_bid, realtime"が0にならないこと。
- そのため、RLのモデル学習時 or 予測時に問題がある。
- これらは別 issueで取り組む

**Comment by HashiReo** [comment]
(PV, energyprice, imbalanceprice)_predict_(bid, realtime) = all 0としたときのグラフが以下
![total_daily_profit](https://github.com/user-attachments/assets/834b78c5-d094-4b5a-952b-a266fa2dd28b)

**Comment by HashiReo** [comment]
同様に
`self.df["totalprofit_realtime[Yen]"] = self.df["energyprofit_realtime[Yen]"] + self.df["imbalancepenalty_realtime[Yen]"]`
`self.df["energyprofit_realtime[Yen]"] = self.df["energyprice_actual[Yen/kWh]"] * self.df["energytransfer_actual_realtime[kWh]"]`
予測計画段階のenergypriceとenergytransferのため
`self.df["energyprofit_realtime[Yen]"] = self.df["energyprice_predict_realtime[Yen/kWh]"] * self.df["energytransfer_realtime[kWh]"]`
だと考える。

**Comment by daisukekodaira** [comment]
@HashiReo めちゃくちゃわかりやすい。ありがとう。強化学習の報酬関数とかの部分は大曽根さんが #111 で修正している部分があるので、それを反映すると良くなる可能性がある。一回お互いがプルリクしてコードをあわせるべき。

**Comment by HashiReo** [comment]
@daisukekodaira 
わかりました。totalprofit_bid, realtimeについて更新しましたが、同様にtotalprofit_actual_bid, realtimeについても更新しないといけなさそうなので、そこも含めて他も検討してみます。また対面MTGの時にすり合わせたいです。

**Comment by HashiReo** [comment]
次に、①`self.df["totalprofit_actual_bid[Yen]"]`と②`self.df["totalprofit_actual_realtime[Yen]"]`について検討する。

①`self.df["totalprofit_actual_bid[Yen]"] = self.df["energyprofit_actual[Yen]"] + self.df["imbalancepenalty_actual_bid[Yen]"]`
"actual_bid"なので`self.df["energyprofit_actual[Yen]"]`ではなく`self.df["energyprofit_actual_bid[Yen]"]`に変更した。
`self.df["energyprofit_actual_bid[Yen]"]`は元々無かったため"result_dataframe.csv"に追加した。
`self.df["energyprofit_actual_bid[Yen]"] = self.df["energyprice_actual[Yen/kWh]"] * self.df["energytransfer_actual_bid[kWh]"]`

②`self.df["totalprofit_actual_realtime[Yen]"] = self.df["energyprofit_actual[Yen]"] + self.df["imbalancepenalty_actual_realtime[Yen]"]`
"actual_realtime"なので`self.df["energyprofit_actual[Yen]"]`ではなく`self.df["energyprofit_actual_realtime[Yen]"]`に変更した。
`self.df["energyprofit_actual_realtime[Yen]"]`は元々無かったため"result_dataframe.csv"に追加した。
`self.df["energyprofit_actual_realtime[Yen]"] = self.df["energyprice_actual[Yen/kWh]"] * self.df["energytransfer_actual_realtime[kWh]"]`

上で変更した後のグラフを以下に示す。
![total_daily_profit](https://github.com/user-attachments/assets/f688b910-38aa-4767-a049-76589c66c321)
0にならず。。

**Comment by HashiReo** [comment]
以降はモデルの学習段階 or 予測段階でのテストを行うためissueを変える。
