### ISSUE TITLE
[10/23~] totalprofitが0になるようなモデル作成 or テストデータ作成

### ISSUE THREAD

**Issue by HashiReo** [SmartGridLab/battery-control-by-reinforcement-learning#121]
## 最終的なゴール
- ① totalprofit_actual_bid
- ② totalprofit_actual_realtime
これらの出力が0になるようなRLモデルを作成 or テストデータを作成する
![total_daily_profit](https://github.com/user-attachments/assets/f688b910-38aa-4767-a049-76589c66c321)

## シナリオ
- price_predict, PV_predict.csvを全て0にする
- RLモデルを「～」で学習する（どのように学習させるかも含めて考える）
- テストデータを「～」で予測する（どのようなテストデータを作成するかを考える）
- 欲しい結果：①②が0となるグラフを得ること

## 関連Issue
以下のIssueから続いている
- [x] #114

**Comment by HashiReo** [comment]
データ：「PVout =0, price = 0.01, imbalance = 200」をtrain_dataとして、input_data2022.csvに1か月間だけ登録し、RLに学習させる。
期待されるシナリオ：以下の2つの要因から、「充放電しない」はず。
 - PVout = 0 のため充電しないはず
 -  imbalanceも200と大きいため放電する予定は立てないはず。

上手くいかない場合：1か月間だけでなく、登録期間を増やし再度行う。

次のシナリオ：PVoutとpriceはそのままでimbalanceを減らしていくとどうなるか？→同じ結果が得られてほしい

**Comment by HashiReo** [comment]
input_data2022.csvに任意のデータを登録するにあたって、csvファイルの日付データで存在しない日付が存在しているため、日付を修正する。(例：2022/04/31)

**Comment by HashiReo** [comment]
さらにRL_env.pyのモデルの学習でも式が
`new_soc = self.soc_list[-1] - (action_value / self.battery_max_cap)`となっているため
`new_soc = self.soc_list[-1] + (action_value / self.battery_max_cap)`プラスに直した。
これで再度学習させてみる。

**Comment by daisukekodaira** [comment]
かなりいい感じに進んでると思う。そして書き方がわかりやすい。素晴らしい。
結果がすぐによくならないから手応えがあまりないかもしれないけど、この辺の手触りのある実装を理解していくことが一番重要です。根気よくこのまま進めてほしいです。

**Comment by HashiReo** [comment]
[x] #122 に新しいIssueとして続きを行う。
ペナルティの設定で必要最低限の動作を満たす強化学習モデルの作成を行う。
