### ISSUE TITLE
[4/30] RL_visualize.pyで価格をグラフ化する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#77]
## 追加したい機能
以下の１日分のグラフを出せるようにする
- 電力価格（energyprice_predict, energyprice_actual）
- インバランス価格（imbalanceprice_predict, imbaranceprice_actual）

## Issueが解決した時に期待される結果
以下のグラフ(完成イメージ)が表示される
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/f633f744-5286-416b-84e9-d705e162a7d8)

## 実装の指針
RL_visualize.pyというファイル名の中にグラフ化を行うmethodを集める。
今回実装する機能はファイルの中の一つのmethodとして実装するのが良さそう。（例：get_price_graph）

## このIssueの必要性
今後、予測結果を改善していく際に視覚化して確認できるよう必要があるため。

## Issue解決の期限
とりあえず4/30

**Comment by HashiReo** [comment]
小平先生

_Jしました

隽
________________________________
差出人: Daisuke Kodaira ***@***.***>
送信日r: 2024年4月23日 13:08
宛先: SmartGridLab/battery-control-by-reinforcement-learning ***@***.***>
CC: 隽 ***@***.***>; Assign ***@***.***>
件名: [SmartGridLab/battery-control-by-reinforcement-learning] RL_visualize.pyで瘠颔哎楗栈工 (Issue #77)


追加したいC能

以下の１日分のグラフを出せるようにする

  *   力瘢energyprice_predict, energyprice_actual）
  *   インバランス瘢imbalanceprice_predict, imbaranceprice_actual）

Issueが解Qしたrに期待されるY果

以下のグラフ(完成イメ`ジ)が表示される
image.png (view on web)<https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/f633f744-5286-416b-84e9-d705e162a7d8>

g装の指

RL_visualize.pyというファイル名の中にグラフ化を行うmethodを集める。
今回g装するC能はファイルの中の一つのmethodとしてg装するのが良さそう。（例：get_price_graph）

このIssueの必要性

今後、予yY果を改善していくHに化して_Jできるよう必要があるため。

Issue解Qの期限

とりあえず4/30

―

**Comment by HashiReo** [comment]
@daisukekodaira 
RL_visualize.pyにdescr_priceとして作成したのですが、うまく動かないため、明日確認していただいてもよろしいでしょうか？

**Comment by daisukekodaira** [comment]
ありがとうございます。一緒に見ましょう。

**Comment by HashiReo** [comment]
RL_visualize.pyにdescr_priceとして関数を作成し、main.pyを実行することでグラフを保存できるようにしました。

ただ、energypriceとimbalancepriceのactualの値が0になってしまっています。
result_inputdata_reference.pyの20行目 data = pd.read_csv("Battery-Control-By-Reinforcement-Learning/input_data2022_all_0.csv")をdata = pd.read_csv("Battery-Control-By-Reinforcement-Learning/input_data2022.csv")に変更してもactualの値が0のままでした。
energyprice_actualとimbalanceprice_actualはどのようにして0以外をcsvファイルに入力できますか？

**Comment by daisukekodaira** [comment]
@HashiReo 
＞energyprice_actualとimbalanceprice_actualはどのようにして0以外をcsvファイルに入力できますか？
ここを変更したってことですよね？それで合ってるはず・・・ですが、何か実装がおかしいのかもしれません。
ちょっと一緒に見てみましょう。。。
<img width="662" alt="image" src="https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/0de376cf-c9f3-4d73-ba04-5cee6bcb7f8e">

**Comment by daisukekodaira** [comment]
@HashiReo これはこれで別のissueとして立てておきます
