### ISSUE TITLE
[6/7 - 6/28] PPO2を実装する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#79]
## 追加したい機能
- 強化学習のアルゴリズムをPPO2へアップデートする（現状はPPO）

## Issueが解決した時に期待される結果
- PPO2を使ったコードでも問題なく動作する
- 性能が改善する（強化学習によって生成された充放電スケジュールによる収益性が改善する）
- 性能の改善がグラフで見れるようになる

## 実装の指針
- RL_train.py -> def dispatch_train()にあるPPOをPPO2に変えればよさそう
[Step1] PPO2に変えて、エラーがでることを確認する。エラーの原因をなんとなく理解して言葉で説明できるようにする。
[Step2] エラーの改修方針について立案。言葉で説明する。
[Step3] 実装を変更
[Step4] エラーがでずにコードの実行が完了する

## このIssueの必要性
- スケジュールによる収益性の改善を行うため

## 補足情報
PPO2とPPOの違いは、GPUを使うかどうからしい。GPUの無いPCだとそもそもPPO2はうまく動作しないかも。

## Issue解決の期限
[Step1] 6/7
[Step2] 6/14
[Step3] 6/21
[Step4] 6/28
↑目標です

**Comment by daisukekodaira** [comment]
- 強化学習のアルゴリズムをPPO2へアップデートする（現状はPPO）

PPOってそもそもなんですか？

-  RL_train.py -> def dispatch_train()にあるPPOをPPO2に変えればよさそう

これ具体的にはどの部分でしょうか？

**Comment by HashiReo** [comment]
1. PPO2はstable_baselinesにしか組み込まれていない
2. そのため既存のstable_baselines3でなく、stable_baselinesをインストールしないといけない
3. stable_baselinesはtensorflow==1.xでしかサポートされていない
4. 現在はtensorflow==2.9.1のため、stable_baselinesは使用できない
5. tensorflow==2.9.1をアンインストールし、tensorflow==1.14.0をインストールしようとすると、エラーが出る。
6. tensorflow==1.14.0はPython3.7まででしかサポートされておらず、現在はPython3.10.14のため使用できない

解決策
1. 現在のPython3.10.14でサポートされているtensorflow==1.xを探す
→tensorflow==1.xの最新であるtensorflow==1.15.4はPython3.7までしかサポートされておらず、不可。
　PPO2を使用したいならPythonのバージョンを下げるしかなさそうだが、それによる弊害は予想がつかない

以上がPPO2に変更しようとしたときの問題点と解決策、それによる弊害です。

**Comment by daisukekodaira** [comment]
必要性が喫緊という感じではないので、一旦closeします。もし今後速度が問題になれば再度OpenしてGPU使えるように書き換えます。
