### ISSUE TITLE
[6/12 - 7/3] realtime機能の実装

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#80]
## 追加したい機能
- 実動作(RL_operation.py)の直前に、PV予測や電力価格予測を再度行い、realtimeでスケジュールを再策定する
<img width="801" alt="image" src="https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/b62b6dfb-041c-4ae4-82c9-2bf52966c0ae">

## Issueが解決した時に期待される結果
- bidで生成されたスケジュールよりも収益性の高い充放電スケジュールが得られる

## 実装の指針
- RL_test.pyu -> class TestModel -> def dispatch_realtime(self, ,,,)という感じで実装する
- [Step1] methodの引数、戻り値、最終的な結果の集計のmethod等を決めて書いてみる(クラス図を見ながら確認)
- [Step2] 動かして、エラーがでないこと、day-aheadのdispatch_testの結果に加えて、dispatch_30m_aheadが従来通り得られることを確認
- [Step3] 下の図の収益性評価の棒グラフ（緑）のデータを作る（1ヶ月通算動作の場合で作る）

## このIssueの必要性
- もともと後藤さんのリアルタイム制御は成績が悪かった。改善が必要であった。
<img width="814" alt="image" src="https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/b2941116-9a16-4c6c-a3d6-da1f73cfb92c">

## Issue解決の期限
[Step1] 2024/6/12 
[Step2] 2024/6/19 
[Step3] 2024/7/03 

実装が難しいと思われるので、期限は長めにとってある。適宜行き詰ったら、不明点を挙げてください。

## 関連Issue
以下のissueが完了したら本Issueへ取り掛かる
- [x] #90

**Comment by HashiReo** [comment]
流れとしては
①現状入力されていない、学習しない結果データと、30分前策定データをresult_dataframe.csvに入力されるようにする
②それをグラフに出力する
という流れでずれていないでしょうか？

**Comment by daisukekodaira** [comment]
> 今後の流れとしては ①現状入力されていない、学習しない結果データと、30分前策定データをresult_dataframe.csvに入力されるようにする ②それをグラフに出力する という流れでずれていないでしょうか？

”学習しない結果データ”がよくわからないけど、30分前策定データが`result_dataframe.csv`に入力されるようになればよい！

- 具体的に実装してほしいこと

`RL_dataframe_manager.py`の中の`get_resultform_df`というmethodの中に、`result_dataframe.csv`に出てくるヘッダーの説明があるので見てみてほしい。こんな感じ：
![image](https://github.com/user-attachments/assets/79f46ec3-e9c0-45df-bf6e-4794342fce06)
この中で、このissueで実装したいのは、`totalprofit_actual_realtime`。これの値を`simulation_result.pdf`のグラフに追加してほしい。`totalprofit_actual_realtime`は`charge/discharge_actual_realtimeの制御実績による売電利益とインバランスペナルティの合計`なので、`charge/discharge_actual_realtime`も計算しておく必要がある。

`_realtime`がついているヘッダーは、用意されいるけど、実質的に計算できていない（はず）です。なので、`totalprofit_actual_realtime`を計算するの必要なものを一つづつ事前に計算する必要があります。細かい計算の内容の理解は後藤さんの修論を読んでみてください。（[Google Drive](https://github.com/SmartGridLab/wiki/blob/master/Tips/99_%E5%90%84%E7%A8%AE%E8%B3%87%E6%96%99.md)にあります）。とはいえ、修論読んだだけでは不明なことも多いと思いますので、小平に適宜相談してください。

**Comment by daisukekodaira** [comment]
result_evaluation.pyの中の計算式をたどって、必要なものを計算するコードを作る。
-> `charge/discharge_actual_realtime[kWh]`がresultcsvの中に書き込まれていることが必要。`charge/discharge_actual_realtime[kWh]`はRL_operate.pyの中で計算されるべきもの。method operate_bidを参考にして、operate_realtimeを作る必要がある。

**Comment by HashiReo** [comment]
totalprofit_actual_realtimeを計算できるように、operate_realtimeを作成する等行ったのですが、weather_data_realtime.pyでエラーが出ているためweather_data_bid.pyを参考にしながら、エラーを直しています

**Comment by HashiReo** [comment]
PV_predict.pyのqd_objective関数（126行目）は引数としてy_true, y_predをもらうはずなのですが、qd_objective関数を使用しているget_LUBE関数(147行目)ではqd_objective関数に対して今のところ何も引数を与えていません。

y_predに関しては200行目にy_pred = model.predict(X_test, verbose=0)と定義があるのですが、y_testに関しては定義すら見当たりません。

y_testをどこから持ってきているか、教えていただきたいです。
<img width="718" alt="スクリーンショット 2024-07-25 11 16 53" src="https://github.com/user-attachments/assets/5fd47a9d-02a5-403e-a5c1-ed3c53a9dce7">

**Comment by HashiReo** [comment]
realtimeのデータを記録できるようにしました。
またmain.pyにてmodeを指定するだけでrealtimeとbidを切り替えられるようにしました。
ここまでをプルリクエストしました。

グラフ化するにあたって、現状はbidとrealtime日程が同じでも別の行で記録されてしまうため、同じ日程のrealtimeとbidのデータを同じ行に記録するようにする。（うまく伝えづらいため、もし不明点あればお願いします）
上ができるようになれば、グラフ化ができる。

**Comment by daisukekodaira** [comment]
@HashiReo 
ナイス！プルリクをマージしました。課題を説明する画像を貼っておきます：
![S__11608100](https://github.com/user-attachments/assets/6c19cf3f-04b0-4b06-beb5-a75e5f293538)


> realtimeのデータを記録できるよう
にしました。 またmain.pyにてmodeを指定するだけでrealtimeとbidを切り替えられるようにしました。 ここまでをプルリクエストしました。
> 
> グラフ化するにあたって、現状はbidとrealtime日程が同じでも別の行で記録されてしまうため、同じ日程のrealtimeとbidのデータを同じ行に記録するようにする。（うまく伝えづらいため、もし不明点あればお願いします） 上ができるようになれば、グラフ化ができる。

**Comment by HashiReo** [comment]
同じ日程のrealtimeとbidの結果を、同じ行にまとめて出力することができました
グラフはおおそねくんが作ってくれたものでいったんは大丈夫かなと思います

**Comment by daisukekodaira** [comment]
ナイス。２つ要望があります。

1. bid modeとrealtime modeの切り替えについて
現状だとmain.pyの最初の部分で手動でmodeを切り替えていると思います。それを自動的に両方のmodeが動作するようにしてください。ただし、後でデバッグできるように、modeの機能自体は残しておいてください。実装は任せます。機能の説明を必ずコメントに入れておいてください。

2. imbaranceの計算を実装する
以下の内容に対応してください。
このIssueの最終目標が以下の通り：
＞[Step3] 下の図の収益性評価の棒グラフ（緑）のデータを作る（1ヶ月通算動作の場合で作る）
そのために必要なこと：result_evaluation.py -> 49行目付近：imbarancepenalty_realtimeを計算するコードを追加する必要がある
Q. どのように埋めるか？
A. bidの方の計算式(imbarancepenalty_bid)をそのまま使う。ただし、energy trade等はrealtimeのデータを使うようにする

**Comment by HashiReo** [comment]
プルリクを送信しました

**Comment by daisukekodaira** [comment]
@HashiReo total_daily_profit.pdfのオレンジのグラフが見えているキャプチャーをここに貼り付けて、issueをcloseしてください！

**Comment by HashiReo** [comment]
[total_daily_profit.pdf](https://github.com/user-attachments/files/17301719/total_daily_profit.pdf)

**Comment by HashiReo** [comment]
https://github.com/HashiReo/battery-control-by-reinforcement-learning/blob/master/Battery-Control-By-Reinforcement-Learning/total_daily_profit.pdf

**Comment by HashiReo** [comment]
[total_daily_profit.pdf](https://github.com/user-attachments/files/17301732/total_daily_profit.pdf)

**Comment by HashiReo** [comment]
![total_daily_profit.pdf](https://github.com/user-attachments/files/17301758/total_daily_profit.pdf)

**Comment by HashiReo** [comment]
![daily_profit](https://github.com/user-attachments/files/17301772/total_daily_profit.pdf)

**Comment by HashiReo** [comment]
![total_daily_profit.pdf](https://github.com/user-attachments/files/17301821/total_daily_profit.pdf)

**Comment by HashiReo** [comment]
![total_daily_profit.pdf](https://github.com/user-attachments/files/17301841/total_daily_profit.pdf)
