### ISSUE TITLE
[7/3] 複数日（１か月）の一括動作を実装する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#84]
## 追加したい機能
- PVの予測と強化学習によるスケジュール策定を1ヶ月連続で動作するようにする

## Issueが解決した時に期待される結果
- result_daraframe.csvに指定した1ヶ月分の結果がresult_dataframe.csvに書き出される。
- 1ヶ月分の蓄電池の充放電動作がグラフ(pdf)で出力される（軸はすべて英語でお願いします） 

## 実装の指針
- main.pyの中に、"OneDay"モードがあるので、それを動作させるように改良する（以下の図を参照）
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/5b0f4465-f507-4de1-80bf-bb5a6defea1d)
- 日付の指定はmain.py内で行っているが、それが適切な実装なのかは不明
- まず２日間連続で動くようにするのを目指す

## このIssueの必要性
- １か月間等の連続した動作の結果を評価するため

## Issue解決の期限
- 2024/5/7を目安に実装する

**Comment by daisukekodaira** [comment]
まず2日間の動作は実装した [pullreq](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/pull/87#issue-2267263327)

**Comment by OsoneYuki** [comment]
実装はしましたがcsvに2日間の結果は出ません。main.pyで指定した日付が他ファイルに影響してないのと、csvが上書きされる設定になっているので。今そこをやってます

**Comment by OsoneYuki** [comment]
main.pyで指定した日付を、testを実行するときに渡すようにしたいのですが、どこに渡せばいいかわからなくて困ってます。

返信は都合の良い時で大丈夫です。

**Comment by daisukekodaira** [comment]
@OsoneYuki 

■どこに渡せばいいか？
・RL_main.pyにわたす -> RL_test.pyにわたす

■コードの構造について
強化学習のtestはRL_test.pyの中のTestModelというクラスの中で行われます。このクラスは、testケースを何パターンか分けて実施することを想定されて作られています。現在はdispatch_testという１つのケース（method）しかありません。
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/75bd0c80-4074-43bd-a7e2-206b5561efe0)

現在の実装では、このRL_test.py(TestModelクラス)は、RL_main.pyから呼ばれる構造になっています。RL_main.pyは強化学習モデルのトレーニング(RL_train.py)とテスト（RL_test.py）を呼び出して、学習とテストを行います。学習を一度行った場合は、RL_trainedModelsというフォルダに学習済みのモデルが入ります。もしここに学習済みモデルがあれば、学習はスキップして、testのみを行います。
dispatch_testはmodel_nameという引数を必要とします。これは保存済み学習モデルのファイル名に当たります。このmodel_nameはRL_main.pyで取得されます。↓
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/aa27fbf6-e297-420c-afd4-41b7d968a68c)

**Comment by OsoneYuki** [comment]
返信ありがとうございます。学習モデルについて大変参考になりました。

<img width="417" alt="スクリーンショット 2024-05-06 164512" src="https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/183bc408-377a-4675-80ce-8c8038873250">

現状、画像のような形で複数日動作はするのですが、RL_dataframe_manager.pyでdf_testdataを生成する際、pv_predict_all_0.csvのデータが8月8日のものしかないため複数日の動作をしても意味がないものになっていると思われます。

**Comment by daisukekodaira** [comment]
@OsoneYuki ok。そうしたら、pv_predict_all_0.csvを１ヶ月分すべて０でいいのでコピーして中身を作ってほしい。全部0のパターンで動くようになったら、真面目に太陽光発電の予測のコードで生成された1ヶ月分が使えるようにしたい。

**Comment by OsoneYuki** [comment]
@daisukekodaira 8月8日からスタートして８月１１日で必ずエラーが出る。
例外が発生しました: ValueError
Expected parameter loc (Tensor of shape (1, 1)) of distribution Normal(loc: tensor([[nan]]), scale: tensor([[1.]])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan]])
  File "/workspaces/battery-control-by-reinforcement-learning/Battery-Control-By-Reinforcement-Learning/RL_test.py", line 46, in dispatch_test
    action, _ = self.model.predict(obs)
  File "/workspaces/battery-control-by-reinforcement-learning/Battery-Control-By-Reinforcement-Learning/RL_main.py", line 49, in <module>
    df_test = testModel.dispatch_test(latestModel_name)
ValueError: Expected parameter loc (Tensor of shape (1, 1)) of distribution Normal(loc: tensor([[nan]]), scale: tensor([[1.]])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan]])

**Comment by daisukekodaira** [comment]
@OsoneYuki 
- result_dataframe.csvに結果が書き出させるように
- データを実際のPV予測のデータを使うように（all0ではなく)

**Comment by OsoneYuki** [comment]
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/cdd61f79-8281-4c9f-9073-de7c5aec9428)
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/7697314e-e284-4ce8-9c29-c4ea1270165e)
all0を使えば一か月分の結果を表示できます。

pv_predict.csvやprice_predict.csvには一日分の結果しか格納されていないのでどうしましょう？

**Comment by daisukekodaira** [comment]
@OsoneYuki 
すばらしい！

> pv_predict.csvやprice_predict.csvには一日分の結果しか格納されていないのでどうしましょう？

pv_predict.csvとprice_predict.csvが1ヶ月分動作するようにしたいです
具体的には、
1) main.py内で、起点の日付と期間（e.g. 30日間）を指定する
2) pv_predictとprice_predictが指定した期間（e.g.30日分)ループして繰り返す
3) 予測結果をpv_predict.csvとprice_predict.csvに書き込む
4) 予測で得られた結果を使って↑のように結果を出す
で、やってみてください！

**Comment by OsoneYuki** [comment]
@daisukekodaira 

![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/4a01c085-8a97-4150-ab0d-b8113601f374)

pv_predict.pyでtestに使用しているdf_wをweather_data.csvから読み込んでいて、そのweather_data.csvのデータが8月8日分しか格納されてないためループができない状況です。
weather_data.csvをどうしますか？

**Comment by daisukekodaira** [comment]
どうしようかね・・・まかせたい！難しそうだったらまた教えて欲しい！

**Comment by daisukekodaira** [comment]
![Class_Diagram](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/5b0cf48d-b02b-4f08-991c-4d285e660f8e)

weather_data.csvは↑の黄色く塗った４つのファイルから作られている。４つすべてのpyファイルを理解して１ヶ月用の動作に修正しなければらない。作業量が多すぎるので、以下の方針で修正する：

■大曽根さんやること
1ヶ月分のweather_dataを手作業で用意する
 - 8/1 - 8/31のcsvを用意して、手作業で結合
pv_predictから手作業で作ったcsvを読む形で動作させる

■小平やること（か、誰か人にまかせること）
1. 後藤さんに聞いて解読する
　　- 各コードが何をやっているのか聞く
　  - １ヶ月分のデータを出すには、どこをどう直せばいいのか聞く

**Comment by OsoneYuki** [comment]
mainを実行して一か月の結果を表示するところまでのプルリクを送りました。
一日ごとのpv,price予測を利用してresult_dataframe.csvに8月1日～31日までの結果を表示します。それ以外の日を予測するにはその日のweatherデータを手作業で取得する必要があります。

**Comment by daisukekodaira** [comment]
@OsoneYuki 
遅くなったけど、今プルリクマージした！任意の日付で出力できるようになるには、何が課題か（weatherデータの生成が課題？）、どうすれば解決できそうなのか相談させてください。

> main.py内で、起点の日付と期間（e.g. 30日間）を指定する

**Comment by daisukekodaira** [comment]
@OsoneYuki 
7/3 話したこと：
・2022年であればmain.pyで日付を指定することで任意の期間の結果が得られるようになったはず
・プルリクしてほしい！（小平が動作確認したり、バグがあれば修正するので～）

**Comment by OsoneYuki** [comment]
@daisukekodaira 
エラーが出てるのでプルリクはもう少し時間がかかりそうです（5日まで）
