### ISSUE TITLE
[5/10, 5/14] der_testerとやりとりするワークフロー図を作る

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#89]
## 追加したい機能
強化学習のアルゴリズムコード(battery-control-by-reinforcement-learning)と蓄電池制御のコード(der_tester)が協調して動く場合のワークフロー図を作る  

## Issueが解決した時に期待される結果
- 以下の図が正確になる（データの流れと動作のタイミング）  

![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/a70dd09a-8c73-453d-9fb1-103d06b37ace)

## 実装の指針
以下のような動作の流れを想定する：
1. der_testerからGWを介して蓄電池のSoCを聞く（getコマンド）
2. der_testerが蓄電池から返答を受け取る
3. der_testerがRL_for_batteryへ現在のSoCの値を渡す
4. RL_for_Batteryが充放電スケジュール(.csv?)を生成する
5. RL_for_Batteryがder_testerへ充放電スケジュールを渡す
6. der_testerがGWを介して蓄電池へ充放電の指令を実現する

## このIssueの必要性
Discussed in https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/discussions/85

## Issue解決の期限
- 2024/05/10　初版 -> ここにのせて小平がコメントする
- 2024/05/14　第２版 -> 初版に対するコメントを反映する

**Comment by OsoneYuki** [comment]
ワークフロー図は以下の文章を、後藤さんが作っていた図のような形に直すという認識でいいですか？

![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/a567b120-8ac1-4491-839c-8454395257bb)

**Comment by daisukekodaira** [comment]
@OsoneYuki そのとおり！

**Comment by OsoneYuki** [comment]
![無記名のファイル](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/043aa506-d9fe-459b-af45-a9e752529dfe)

ひとまず作ってみました。

**Comment by daisukekodaira** [comment]
@OsoneYuki 
ナイス。俺も理解が深まった。ありがとうございます。以下の点を修正して欲しい：
・一番最初にRL_for_Batteryがder_testerに制御可能かどうかを聞く動作を入れる
・指令を実行した結果をRL_for_batteryの方で受け取れるようにする（そして次のタイムステップでその情報が使えるようにする）
コードを実装する時のことをイメージして書いてもらえると嬉しいです。

あと、この絵を直接編集できるようにBoadmixの共有URLみたいなのが欲しいです。

**Comment by OsoneYuki** [comment]
@daisukekodaira 
共有URL
https://boardmix.com/app/share/CAE.CNX6ICAFKhZLQnc3cUZVU0ctYkJUUU9CVGJJWDBnMAVAAQ，リンクをクリックして、Boardmix のチーム「私の最初のチーム」に参加してください。

確認お願いします。

![無記名のファイル](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/130620546/b0d3074b-9b03-47f5-a688-5c6b9f2671b5)

**Comment by daisukekodaira** [comment]
@OsoneYuki 
完璧。URLもありがとう！
