### ISSUE TITLE
[5/3 - 5/21] コード全体のclass diagramを生成する

### ISSUE THREAD

**Issue by daisukekodaira** [SmartGridLab/battery-control-by-reinforcement-learning#90]
## 追加したい機能
- battery-control-by-reinforcement-learningのコード全体が俯瞰できるようなclass diagram(クラス図)を作る

## Issueが解決した時に期待される結果
- こんな感じの図が得られる
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/43132698/bc6628f3-0eb5-4528-abec-06aa70f04b81)

## 実装の指針
- まずクラス図とは何かを理解する [クラス図とは](https://qiita.com/hukuryo/items/4d8c3d1f3d3e0cab6589)
- VScodeのextentionを使って自動生成できないか確認する(e.g. [APPMap](https://marketplace.visualstudio.com/items?itemName=appland.appmap))
- 自動生成がうまくいかなければ、コードを見ながら自分で作ってみる
- 完璧なものは無理なので、とりあえず全体を雑に概観するものを作る（クラスを列挙だけして依存関係はとりあえず適当など）
- ファイルの関係性・クラス名・関数名をとりあえず列挙する、関連していないファイルも単独で記述する

## このIssueの必要性
- 今後改修していくのにどこをどう直せばいいのか分からないので

## Issue解決の期限
- 2024/05/03 初版
- 2024/05/07 第2版
- 2024/05/14 第3版
- 2024/05/21 第4版 -> 完成したら嬉しい

## 関連Issue
#82, #80

**Comment by HashiReo** [comment]
APPMAPで試してみたのですが、難問だったのでコードを書いてクラス図を作成する方向で行きます

**Comment by daisukekodaira** [comment]
手書きでもいいのでとりあえず何か成果物をください。それがあれば具体的に何をどうすればいいのかの話が始められるので。。。

**Comment by HashiReo** [comment]
わかりました。APPMAPで行ったことをまとめてまた報告します。

**Comment by HashiReo** [comment]
https://docs.google.com/document/d/15LKYIpjBIFCAGAeJ_jC55zsduK_EhYuJ7wukyu9RuSg/edit?usp=sharing
documentに現状の流れを示しました。
今のところ、どこをどう直せばよいかわからない状況です。。

**Comment by daisukekodaira** [comment]
色々試してくれてありがとう。
＞appmap python packageを使ってコードをRecordする
っということの詳しい内容が[ここ](https://appmap.io/docs/reference/appmap-python.html#context-manager-recording)に乗ってるけど複雑すぎてわけわからんね・・・pytestとかをつかって単体テストが実装されているコードなら簡単にできそうだけど、今俺達が開発しているコードは（残念ながら）そうなっていない。

結論からいうと、AppMapはあきらめて、自分で手書きでまず作ってみてほしい。
今の実装だと、pythonの一つずつのファイルにだいたいクラスが一つはいっていると思います。
それをつなげてほしい（引数が何か調べながら）

**Comment by HashiReo** [comment]
わかりました。とりかかります

**Comment by HashiReo** [comment]
クラス図をvscodeの拡張機能である、PlantUMLを使って作成します。
PlantUMLを作成する際にJavaとgraphvizの二つが必要となるのですが、dockerへのインストール等をお会いしたタイミングで教えていただきたいです

**Comment by HashiReo** [comment]
linuxにjavaとgraphvizをインストールし、vscodeのextensionとしてPlantUMLをインストールしました。
sample.pumlとしてサンプルクラス図を作成できました。
![image](https://github.com/SmartGridLab/battery-control-by-reinforcement-learning/assets/160702017/08f2651e-9bfa-41c6-ac00-d7f2dde5954d)

サンプルができたので全体のクラス図にとりかかります

**Comment by HashiReo** [comment]
クラスがなく関数だけの.pyファイルもあるのですがいったんそこは無視で進めますか？

**Comment by daisukekodaira** [comment]
#105 完了
